services:
 postgres:
  image: postgres:16
  environment:
   POSTGRES_DB: analyzerdb
   POSTGRES_USER: botuser
   POSTGRES_PASSWORD: botpass
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  restart:
   unless-stopped
 
volumes:
 postgres_data: