name: post-analyzer

services:
   postgres:
      image: postgres:16
      environment:
         POSTGRES_DB: analyzerdb
         POSTGRES_USER: analyzeruser
         POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
         - "5432:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data
      restart: unless-stopped

volumes:
   postgres_data:
